[package]
name = "colorator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = "4.5.1"
minijinja = { version = "1.0.12", features = ["loader"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

